### PR TITLE
OSSM-2419 Prevent deadlock

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
@jwendell what's wrong here.. looks like the builder image is missing something?

**Comment by jwendell** [comment]
I think we need https://github.com/maistra/api/commit/b697cfbcb1c04805a352209705d3c7d0401063c8 in 2.3

**Comment by jwendell** [comment]
@luksa can you cherry-pick it as part of this PR as a separate commit? You can try it locally using the 2.3 builder image too.

**Comment by luksa** [comment]
@jwendell we need to keep `go mod vendor`, right (https://github.com/maistra/api/commit/b697cfbcb1c04805a352209705d3c7d0401063c8 removes it)?

**Comment by jwendell** [comment]
> @jwendell we need to keep `go mod vendor`, right ([b697cfb](https://github.com/maistra/api/commit/b697cfbcb1c04805a352209705d3c7d0401063c8) removes it)?

That commit itself doesn't remove it I think. I tried to keep commits separated in 2.4 PR (https://github.com/maistra/api/pull/40). That said, yeah, maybe you need to do some adjustments for 2.3.

**Comment by luksa** [comment]
`make gen` previously did a `go mod vendor`, but the commit removes this... I've now modified the cherry-picked commit so it still runs `go mod vendor`.

**Comment by jwendell** [comment]
> `make gen` previously did a `go mod vendor`, but the commit removes this... I've now modified the cherry-picked commit so it still runs `go mod vendor`.

Thanks, that was my mistake. That removal should be part of the other commit that removes vendor dir.

**Comment by luksa** [comment]
@jwendell I think that change now makes everything worse :)

**Comment by jwendell** [comment]
ok, let me try it locally

**Review by jwendell — APPROVED** [review]

**Comment by luksa** [comment]
Oops, forgot the don't squash label... but too late now.

**Pull request merged**
