### PR TITLE
Fix typo in ServiceImportExportLabelelector

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
shouldn't the docs be updated automatically?

**Comment by luksa** [comment]
Looks like there's a bug in the doc generation. There's no documentation generated for array fields. For example, see the Type column at https://github.com/maistra/api/blob/maistra-2.1/docs/crd/maistra.io_ServiceExports_v1.adoc#serviceexportsspec. The `[]ServiceExportRule` should be a link, but isn't.

**Comment by luksa** [comment]
Filed https://issues.redhat.com/browse/MAISTRA-2510 for the missing links.

**Review by jwendell — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Comment by jwendell** [comment]
@luksa We need to fix istio repository too: https://github.com/maistra/istio/pull/406 - Feel free to close this automated PR and provide a correct one.

**Pull request merged**
